# Generated by Django 4.2.3 on 2023-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=10)),
                ('dietary_restrictions', models.TextField(max_length=200)),
                ('affiliation', models.CharField(choices=[('CC', 'zhongwentang'), ('OIF', 'OIF')], max_length=3)),
                ('small_group', models.CharField(choices=[('Oasis', 'Oasis')], max_length=10)),
            ],
        ),
    ]
